name: a_mem

backend: openai
llm_model: qwen/qwen3-vl-8b-instruct
llm_api_key: ""
llm_api_key_env: OPENROUTER_API_KEY
llm_base_url: "https://openrouter.ai/api/v1"
retrieve_k: 10
embedding_model: all-MiniLM-L6-v2
caption_preprocessed: true
temperature_c5: 0.5
